# Site settings
author: ROBERT  ALEDO
title: 
header-img: img/home-bg.png
email: robertaledo22@gmail.com
copyright_name: ROBERT  ALEDO
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Robaledo26

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
